package ca.mcgill.ecse321.android_has;

import android.support.v4.app.FragmentManager;
import android.content.Intent;
import android.support.v4.app.Fragment;
import android.os.Bundle;
import android.support.design.widget.NavigationView;
import android.support.v4.view.GravityCompat;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBarDrawerToggle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.MenuItem;
import android.view.View;

import java.util.ArrayList;
import java.util.List;

import ca.mcgill.ecse321.HAS.controller.HASController;
import ca.mcgill.ecse321.HAS.model.Album;
import ca.mcgill.ecse321.HAS.model.Artist;
import ca.mcgill.ecse321.HAS.model.HAS;
import ca.mcgill.ecse321.HAS.model.Song;
import ca.mcgill.ecse321.android_has.albums.AddAlbumActivity;
import ca.mcgill.ecse321.android_has.albums.AlbumNavFragment;
import ca.mcgill.ecse321.android_has.artists.AddArtistActivity;
import ca.mcgill.ecse321.android_has.artists.ArtistNavFragment;
import ca.mcgill.ecse321.android_has.playlists.AddPlaylistActivity;
import ca.mcgill.ecse321.android_has.playlists.PlaylistNavFragment;
import ca.mcgill.ecse321.android_has.roomgroups.AddRoomGroupActivity;
import ca.mcgill.ecse321.android_has.roomgroups.RoomGroupNavFragment;
import ca.mcgill.ecse321.android_has.rooms.AddRoomActivity;
import ca.mcgill.ecse321.android_has.rooms.RoomNavFragment;
import ca.mcgill.ecse321.android_has.songs.AddSongActivity;
import ca.mcgill.ecse321.android_has.songs.SongNavFragment;

public class MyMusicActivity extends AppCompatActivity
        implements NavigationView.OnNavigationItemSelectedListener {


    private Fragment currentFragment;

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        //autogenerated code
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_my_music);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(
                this, drawer, toolbar, R.string.navigation_drawer_open, R.string.navigation_drawer_close);
        drawer.setDrawerListener(toggle);
        toggle.syncState();

        NavigationView navigationView = (NavigationView) findViewById(R.id.nav_view);
        navigationView.setNavigationItemSelectedListener(this);

        //Sets the song view as the default on startup
        if(HASAndroidApplication.getCurrentMenu() == null)
            HASAndroidApplication.setCurrentMenu(navigationView.getMenu().getItem(2));
        HASAndroidApplication.getCurrentMenu().setChecked(true);
        onNavigationItemSelected(HASAndroidApplication.getCurrentMenu());
    }

    @Override
    public void onResume() {
        super.onResume();
        HASAndroidApplication.getCurrentMenu().setChecked(true);
        onNavigationItemSelected(HASAndroidApplication.getCurrentMenu());
    }


    @Override
    public void onBackPressed() {
        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        if (drawer.isDrawerOpen(GravityCompat.START)) {
            drawer.closeDrawer(GravityCompat.START);
        } else {
            super.onBackPressed();
        }
    }

    @SuppressWarnings("StatementWithEmptyBody")
    @Override
    public boolean onNavigationItemSelected(MenuItem item) {

        HASAndroidApplication.setCurrentMenu(item);

        int id = item.getItemId();
        currentFragment = null;

        switch (id){
            case R.id.nav_artists:
                currentFragment = new ArtistNavFragment();
                setTitle("Artists");
                break;

            case R.id.nav_albums:
                currentFragment = new AlbumNavFragment();
                setTitle("Albums");
                break;

            case R.id.nav_songs:
                currentFragment = new SongNavFragment();
                setTitle("Songs");
                break;

            case R.id.nav_playlists:
                currentFragment = new PlaylistNavFragment();
                setTitle("Playlists");
                break;

            case R.id.nav_rooms:
                currentFragment = new RoomNavFragment();
                setTitle("Rooms");
                break;

            case R.id.nav_room_groups:
                currentFragment = new RoomGroupNavFragment();
                setTitle("Room Groups ");
                break;
        }

        //sets the new currentFragment
        FragmentManager fragmentManager = getSupportFragmentManager();
        fragmentManager.beginTransaction().replace(R.id.content_container, currentFragment).commit();

        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        drawer.closeDrawer(GravityCompat.START);
        return true;
    }

    public void addArtist(View v) {
        Intent intent = new Intent(this, AddArtistActivity.class);
        startActivity(intent);
    }

    public void addAlbum(View v) {
        Intent intent = new Intent(this, AddAlbumActivity.class);
        startActivity(intent);
    }

    public void addSong(View v) {
        Intent intent = new Intent(this, AddSongActivity.class);
        startActivity(intent);
    }

    public void addPlaylist(View v) {
        Intent intent = new Intent(this, AddPlaylistActivity.class);
        startActivity(intent);
    }

    public void addRoom(View v) {
        Intent intent = new Intent(this, AddRoomActivity.class);
        startActivity(intent);
    }

    public void addRoomGroup(View v) {
        Intent intent = new Intent(this, AddRoomGroupActivity.class);
        startActivity(intent);
    }

    public void sortByAlbum(View v) {
        HASController hc = new HASController();
        HAS h = HAS.getInstance();
        hc.sortAlbums();
        List<Song> songsSortedByAlbum = new ArrayList<Song>();

        for(Album a: h.getAlbums()) {
            songsSortedByAlbum.addAll(a.getSongs());
        }

        assert currentFragment instanceof SongNavFragment;
        ((SongNavFragment) currentFragment).setSongs(songsSortedByAlbum);
    }

    public void sortByArtist(View v) {
        HASController hc = new HASController();
        HAS h = HAS.getInstance();
        hc.sortArtists();
        List<Song> songsSortedByArtist = new ArrayList<Song>();
        for(Artist ar : h.getArtists()) {
            for(Album al: ar.getAlbums()) {
                songsSortedByArtist.addAll(al.getSongs());
            }
        }
        assert currentFragment instanceof SongNavFragment;
        ((SongNavFragment) currentFragment).setSongs(songsSortedByArtist);
    }
}
